name: New feature requests
description: A new feature is required.
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this report!
  - type: textarea
    id: what-needed
    attributes:
      label: Please describe your requirements in detail.
      description: For example, certain request interfaces may be missing, which is usually caused by version updates or the addition of certain necessary new features.
      placeholder: Please describe your requirements in detail.
    validations:
      required: true
  - type: dropdown
    id: urgency
    attributes:
      label: How urgent is it?
      multiple: false
      options:
        - Low
        - Middle
        - High
      default: 0
    validations:
      required: true